06_WEB/0828/django_methods/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog_app'

urlpatterns = [
    # blog 앱 내부의 경로를 지정할 부분
    # path('', views.index), # localhost:8000/blog 경로, 경로를 호출하면 실행할 함수의 위치
    path('post-list', views.PostList.as_view(), name='post_list'),
    path('', views.about_me, name='about_me'),
    path('<int:pk>', views.PostDetail.as_view()), # <자료형:필드명> 
    path('create-post/', views.PostCreate.as_view())
]

06_WEB/0828/django_methods/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.db import models

# Tag table 작성 - pk는 자동 생성됨
class Tag(models.Model):
    tag_name = models.CharField(max_length=30, unique=True)
    # 짧은 라벨로서, 문자, 숫자, 밑줄 또는 하이픈만을 포함. 일반적으로 URL에 사용.  
    slug = models.SlugField(max_length=30, unique=True, allow_unicode=True)

    def __str__(self):
        return self.tag_name
    
    def get_absolute_url(self): 
        return f'/blog/tag/{self.slug}'


# Create your models here.
# models모듈의 Model 클래스를 상속받는 자식클래스 생성
# 게시글에 필요한 필드는 무엇무엇일까요
class Post(models.Model): 
    title = models.CharField(max_length=50)
    content = models.TextField()
		
	# django model 이 최초 저장(insert) 시에만 현재날짜(date.today()) 를 적용
    # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    created_at = models.DateTimeField(auto_now_add=True) # now()
	# django model 이 save 될 때마다 현재날짜(date.today()) 로 갱신됨
    updated_at = models.DateTimeField(auto_now=True) 

    head_image = models.ImageField(upload_to='blog/images/%Y/%m/%d/', blank=True)
    
    # 외래키와 프라이머리키의 관계
    # CASCADE - User가 삭제되면 관련있는 Post 테이블의 모든 글이 삭제
    # SET_NULL - User가 삭제되면 관련있는 Post 테이블의 모든 글에 author 항목은 NULL로 바뀜
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return f'[[{self.pk}] {self.title}]'
		
    def get_absolute_url(self): 
        return f'/blog/{self.pk}'




class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)  # 하나의 포스트에 여러개의 댓글 관계
    author = models.ForeignKey(User, on_delete=models.CASCADE) # 여러 사람이 하나의 댓글창에 댓글 구현 가능
    content = models.TextField()
    
    # 아예 값 자체가 지금 시간으로 입력되어 들어감(우리가 변경할 필요 없음)
    created_at = models.DateTimeField(auto_now_add=True) # now()
	# django model 이 save 될 때마다 현재날짜(date.today()) 로 갱신됨
    updated_at = models.DateTimeField(auto_now=True) 

    def __str__(self):
        return f'[[{self.pk}] {self.content}]'
		
    def get_absolute_url(self): 
        return f'{self.post.get_absolute_url()}#comment-{self.pk}' # #을 단 이유 : html에서 ID 

06_WEB/0828/django_methods/blog/forms.py
from .models import Comment

06_WEB/0828/django_methods/blog/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from .models import Post
from django.views.generic import ListView, DetailView, CreateView


class PostCreate(CreateView):
    model = Post 
    fields = ["title", "content", "head_image"]

    # CreateView가 내장한 함수 - 오버라이딩 
    # tag는 참조관계이므로 Tag 테이블에 등록된 태그만 쓸 수 있는 상황
    # 임의로 방문자가 form에 Tag를 달아서 보내도록 form_valid()에 결과를 임시로 담아두고
    # 저장된 포스트로 돌아오도록 
    # def form_valid(self, form):
    #     current_user = self.request.user
    #     if current_user.is_authenticated and (current_user.is_staff or current_user.is_superuser):
    #         form.instance.author = current_user
    #         response = super(PostCreate, self).form_valid(form)

    #         tags_str = self.request.POST.get('tags_str')
    #         if tags_str:
    #             tags_str = tags_str.strip()   # 책, 독후감, 작가명

    #             tags_str = tags_str.replace(',', ';')
    #             tags_list = tags_str.split(';')

    #             for t in tags_list:
    #                 t = t.strip()
    #                 tag, is_tag_created = Tag.objects.get_or_create(tag_name=t)
    #                 if is_tag_created:
    #                     tag.slug = slugify(t, allow_unicode=True)
    #                     tag.save()
    #                 self.object.tag.add(tag)

    #         return response

    #     else:
    #             return redirect('/blog/')


    #    return super().form_valid(form)
    
class PostDetail(DetailView):
    model = Post 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = '임의로 작성한 새로운 변수'
        print(context["now"] )
        return context

class PostList(ListView):   # post_list.html, post-list
    model = Post 
    # template_name = 'blog/index.html' 
    ordering = '-pk' 
    context_object_name = 'post_list'

def index(request): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    posts = Post.objects.all()
    return render(
        request,
        'blog/index.html', {
            'posts':posts, 'my_list': ["apple", "banana", "cherry"], 'my_text': "첫번째 줄 \n 두번째 줄", 'content' : '<img src="data/jjangu.jpg" / >'
        }
    )# 없는 index.html을 호출하고 있음

def about_me(request): # 함수를 만들고, 그 함수를 도메인 주소 뒤에 달아서 호출하는 구조
    return render(
        request,
        'blog/about_me.html'
    )

06_WEB/0828/django_methods/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About 김연지</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <style>
        /* The navigation bar */
        .navbar {
            overflow: hidden;
            background-color: #333;
            position: fixed;
            /* Set the navbar to fixed position */
            top: 0;
            /* Position the navbar at the top of the page */
            width: 100%;
            /* Full width */
        }
    </style>
</head>

<body>

    <!-- Header-->
    <div id="header" class="py-5">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
            <div class="container px-5">
                <a class="navbar-brand">YEONJI KIM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"><span
                        class="navbar-toggler-icon"></span></button>
                <!-- <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog_app:about_me' %}">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'blog_app:post_list' %}">Developer</a>
                        </li>
                        <li class="nav-item"><a class="nav-link" href="#three">Technical Editor</a></li>
                    </ul>
                </div> -->

                {# #}
                {% if user.is_authenticated %}
                {{ user.username }}님 환영합니다.
                <a href="{% url 'account:logout' %}">로그아웃</a>
                {% else %}
                <a href="{% url 'account:login' %}">로그인</a>
                <a href="#{% url 'account:signup' %}">회원가입</a>
                {% endif %}
                {# #}

            </div>
        </nav>
    </div>

    {% block page_area %}

    {% endblock %}

    <!-- Footer-->
    <div id="footer" class="bg-dark py-4 mt-auto">
        <div class="container px-5">
            <div class="row align-items-center justify-content-between flex-column flex-sm-row">
                <div class="col-auto">
                    <div class="small m-0 text-white">Copyright &copy; YEONJIKIM 2024</div>
                </div>
                <div class="col-auto">
                    <span class="text-white mx-1">atangi@naver.com</span>
                    <span class="text-white mx-1">&middot;</span>
                    <a class="link-light small" href="mailto:atangi@naver.com">Contact</a>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>

</body>

</html>

06_WEB/0828/django_methods/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page_area %}

                            <!-- Post content-->
                            <article>
                                <!-- Post header-->
                                <header class="mb-4">
                                    <!-- Post title-->
                                    <h1 class="fw-bolder mb-1">{{ post.title }}</h1>
                                    <!-- Post meta content-->
                                    <div class="text-muted fst-italic mb-2">{{ post.created_at }}</div>
                                    <!-- Post categories-->
                                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Web Design</a>
                                    <a class="badge bg-secondary text-decoration-none link-light" href="#!">Freebies</a>
                                </header>
                                <!-- Preview image figure-->
                                {% if post.header_img %}
                                <figure class="mb-4">
                                    <img class="img-fluid rounded" src="{{ post.header_img.url }}" alt="..." /></figure>
                                {% endif %}
                                    <!-- Post content-->
                                <section class="mb-5">
                                    <p class="fs-5 mb-4"> {{ post.content }}</p>
                                    {% if post.file_upload %}
                                    <a href="{{ post.file_upload.url }}" class="btn btn-dark">다운로드</a>
                                    {% endif %}
                                </section>
                            </article>
{% endblock %}

06_WEB/0828/django_methods/blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page_area %}

<div class="row d-flex justify-contents-center">
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</div>
{% endblock %}

06_WEB/0828/django_methods/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page_area %}
{% for p in post_list %}
<!-- bootstrap에서 card 가져오기 -->
<div class="card d-flex justify-content-between" style="width: 60rem;">
    {% if p.head_image %}
    <img src="{{ p.head_image.url}}" class="card-img-top" alt="...">
    <!-- 장고는 이미지 업로드를 위한 ImageField를 제공함.  -->
    {% endif %}
    <div class="card-body">
        <h5 class="card-title"><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h5>
        <h6> {{ p.created_at }} </h6>
        <p class="card-text">{{ p.content }}</p>
        <div class="card-end">
            <span>#작성자명</span>
            <a href="{{ p.get_absolute_url }}" class="btn btn-dark">더 보기</a>
        </div>
    </div>

    {% endfor %}
    {% endblock %}